force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>players properties</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age player</description>
    <label>Age</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Players position</description>
    <label>Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Goalkeeper</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Midfield</fullName>
            </value>
            <value>
                <fullName>Forward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Player__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value player of market</description>
    <label>Value</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PlayersServices.cls
public with sharing class PlayersServices {
 
    @AuraEnabled(cacheable=true)
    public static List<Player__c> getFilteredPlayers(String searchName){
        String searchText = '%'+ searchName + '%';

        return[SELECT id,Name,Image__c,Position__c,Age__c,Value__c 
               FROM Player__c
               WHERE Name LIKE :searchText
               WITH SECURITY_ENFORCED
               ORDER BY Name
               ];
               
               
               //    String myTestString = 'TestName';
               //   List<sObject> sobjList = Database.query('SELECT Id FROM MyCustomObject__c WHERE Name = :myTestString');
    }


}